### ISSUE TITLE
Logstash can't find the prune filter

### ISSUE THREAD

**Issue by slavik57** [logstash-plugins/logstash-filter-prune#20] opened 2017-08-08 06:51 UTC
I have a problem using the filter in the simplest way.
I run logstash on Docker so reproducing should be easy

My docker file:

```
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.5.0

#Install plugins
RUN logstash-plugin install logstash-input-http
RUN logstash-plugin install logstash-filter-prune
RUN logstash-plugin install logstash-filter-drop
```

MY logstash filter section config:
```
filter {
	prune {
		blacklist_values => ["_IS_UNDEFINED$"]
	}
}
```

The error I get when I stard the container:
```
[ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"filter", :name=>"prune", :path=>"logstash/filters/prune", :error_
message=>"NameError", :error_class=>NameError, :error_backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:226:in `namespace_lookup'", "/usr/share/logstash/l
ogstash-core/lib/logstash/plugins/registry.rb:162:in `legacy_lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:138:in `lookup'", "/usr/share/logstash/logsta
sh-core/lib/logstash/plugins/registry.rb:180:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/usr/share/logstash/logstash-cor
e/lib/logstash/pipeline.rb:100:in `plugin'", "(eval):16:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:72:in
`initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:156:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:286:in `create_pipeline'", "/u
sr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:314:in `execute'", "/usr/share/logstash/vend
or/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:209:in `run'", "/usr/share/logstash/vendor/bundle/jrub
y/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

Am I missing something?

**Comment by magnusbaeck** [comment] 2017-08-20 20:18
I can't reproduce this. Please get back with a full recipe for reproducing what you're getting.

```plain
$ cat > Dockerfile
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.5.0

#Install plugins
RUN logstash-plugin install logstash-input-http
RUN logstash-plugin install logstash-filter-prune
RUN logstash-plugin install logstash-filter-drop
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM docker.elastic.co/logstash/logstash:5.5.0
5.5.0: Pulling from logstash/logstash
e6e5bfbc38e5: Already exists 
59d1556260fa: Pull complete 
91d5266b6948: Pull complete 
c32dd4db3cd1: Pull complete 
d210d6f6881d: Pull complete 
318cfb2a8c70: Pull complete 
bdbd51e7d7ab: Pull complete 
a933d333f385: Pull complete 
5e0c8e3445bf: Pull complete 
937321c828f8: Pull complete 
0b6b5b6e1221: Pull complete 
Digest: sha256:ac9339ff2b4dcd329f1c6cea30e94b905f60b75a873676ebc3b6e69e0aa5d884
Status: Downloaded newer image for docker.elastic.co/logstash/logstash:5.5.0
 ---> a60a8b1a3adb
Step 2/4 : RUN logstash-plugin install logstash-input-http
 ---> Running in 607ba5aafbca
Validating logstash-input-http
Installing logstash-input-http
Installation successful
 ---> 9790ab2bf963
Removing intermediate container 607ba5aafbca
Step 3/4 : RUN logstash-plugin install logstash-filter-prune
 ---> Running in f0c92b848536
Validating logstash-filter-prune
Installing logstash-filter-prune
Installation successful
 ---> 78856c8273a9
Removing intermediate container f0c92b848536
Step 4/4 : RUN logstash-plugin install logstash-filter-drop
 ---> Running in fa7094f9fbff
Validating logstash-filter-drop
Installing logstash-filter-drop
Installation successful
 ---> f7389d4cb6f7
Removing intermediate container fa7094f9fbff
Successfully built f7389d4cb6f7
$ cat > test.config
input { stdin { } }
output { stdout { codec => rubydebug } }
filter {
	prune {
		blacklist_values => ["_IS_UNDEFINED$"]
	}
}
$ docker run -it -v $(pwd)/test.config:$(pwd)/test.config f7389d4cb6f7 -f $(pwd)/test.config
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
[2017-08-20T20:15:03,341][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
[2017-08-20T20:15:03,344][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
[2017-08-20T20:15:03,368][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"1ab17a90-1777-40d3-8191-8b26d8f6459f", :path=>"/usr/share/logstash/data/uuid"}
[2017-08-20T20:15:03,834][ERROR][logstash.filters.prune   ] Invalid setting for prune filter plugin:

  filter {
    prune {
      # This setting must be a hash
      # This field must contain an even number of items, got 1
      blacklist_values => ["_IS_UNDEFINED$"]
      ...
    }
  }
[2017-08-20T20:15:03,839][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Something is wrong with your configuration."}
[2017-08-20T20:15:04,090][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash_system:xxxxxx@elasticsearch:9200/]}}
[2017-08-20T20:15:04,092][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash_system:xxxxxx@elasticsearch:9200/, :path=>"/"}
[2017-08-20T20:15:04,196][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x523a53d3>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch: Name or service not known"}
[2017-08-20T20:15:04,197][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<Java::JavaNet::URI:0x3218c6a6>]}
[2017-08-20T20:15:04,198][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>2}
[2017-08-20T20:15:04,200][INFO ][logstash.pipeline        ] Pipeline .monitoring-logstash started
[2017-08-20T20:15:04,275][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-20T20:15:07,215][WARN ][logstash.agent           ] stopping pipeline {:id=>".monitoring-logstash"}
```

**Comment by amithGitHck** [comment] 2017-12-21 11:22
@slavik57 I had similar error
[ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"filter", :name=>"prune", :path=>"logstash/filters/prune", :error_message=>"NameError", :error_class=>NameError, :error_backtrace=>["

The issue was resolved after installing the prune filter plugin.
Install the plugin by running :
bin/logstash-plugin install logstash-filter-prune

**Comment by magnusbaeck** [comment] 2017-12-21 11:39
Not able to reproduce; closing.

**Closed as completed by magnusbaeck** 2017-12-21 11:39 UTC
Labels: needs details

**Comment by T3rm1** [comment] 2018-02-20 15:00
Just for info. I have the same problem with Logstash 5.4.3. prune filter is not installed. Error message as above. This is a normal installation though, no docker.
